### ISSUE TITLE
It's not launching.

### ISSUE THREAD

**Issue by Xasion** [pawel02/music_bot#2]
PS C:\Users\danie\Desktop\Xasion's Music Bot\discord bot> python main.py
Traceback (most recent call last):
  File "C:\Users\danie\Desktop\Xasion's Music Bot\discord bot\main.py", line 19, in <module>
    bot.run(os.getenv("TOKEN"))
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 723, in run
    return future.result()
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 665, in start
    await self.login(*args, bot=bot)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 511, in login
    await self.http.static_login(token.strip(), bot=bot)
AttributeError: 'NoneType' object has no attribute 'strip'

What do i do?

**Comment by pawel02** [comment]
This is most likely because you do not have the TOKEN environment variable set. On Windows you'd first run the command 
`SET TOKEN=Discord_Bot_Token` before running `python main.py`
