### ISSUE TITLE
Hello, I started getting an error.

### ISSUE THREAD

**Issue by HamyZz** [pawel02/music_bot#5]
I have changed code a little bit for me but it didn't affect the code much and its worked for about a month then i started getting an error.
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
[download] Downloading playlist: levan polka
[youtube:search] query "levan polka": Downloading page 1
[youtube:search] playlist levan polka: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] S4nwKLxEboo: Downloading webpage
[youtube] Downloading just video S4nwKLxEboo because of --no-playlist
[download] Finished downloading playlist: levan polka
Ignoring exception in command myus:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\User\Desktop\JavaH\music_cog.py", line 136, in skip
    await self.play_music(ctx)
  File "C:\Users\User\Desktop\JavaH\music_cog.py", line 67, in play_music
    self.vc.play(discord.FFmpegPCMAudio(m_url, **self.FFMPEG_OPTIONS), after=lambda e: self.play_next())
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\player.py", line 225, in __init__
    super().__init__(source, executable=executable, args=args, **subprocess_kwargs)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\player.py", line 138, in __init__
    self._process = self._spawn_process(args, **kwargs)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\player.py", line 147, in _spawn_process
    raise ClientException(executable + ' was not found.') from None
discord.errors.ClientException: ffmpeg was not found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientException: ffmpeg was not found.

**Comment by SamuelFrankSmith** [comment]
You're missing the ffmpeg package. 

My project wasn't recognizing it when downloaded within PyCharm > File >Settings > Python Interpreter > `+`. 

I had to download the binary/executable (https://ffmpeg.org/download.html) and include that directly in my project (at the root).

**Comment by HamyZz** [comment]
> 

I think I have downloaded ffmpeg, because it worked for a month. And CMD says that all requirement for ffmpeg already satisfied.

**Comment by HamyZz** [comment]
> You're missing the ffmpeg package.
> 
> My project wasn't recognizing it when downloaded within PyCharm > File >Settings > Python Interpreter > `+`.
> 
> I had to download the binary/executable (https://ffmpeg.org/download.html) and include that directly in my project (at the root).

And can you please share your code where you have included ffmpeg?

**Comment by HamyZz** [comment]
How I understood, ffmpeg was blocked or smth like that :(
